name: CI Pipeline

on:
  pull_request:
    paths:
      - 'encryption_backend/**'
      - 'encryption_frontend/**'
    branches:
      - main

jobs:
  backend-test:
    runs-on: ubuntu-latest
    container:
      image: node:23

    defaults:
      run:
        working-directory: encryption_backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install backend dependencies
        run: npm install

      - name: Build backend
        run: npm run build

  frontend-test:
    runs-on: ubuntu-latest
    container:
      image: node:23

    defaults:
      run:
        working-directory: encryption_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install frontend dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
