name: Backend CI

on:
  pull_request:
    paths:
      - 'encryption_backend/**'
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:23

    defaults:
      run:
        working-directory: encryption_backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run backend dev server
        run: npm run dev
